import Head from 'next/head';
import Image from 'next/image';
import TournamentNavigation from '../../../components/TournamentNavigation';
import Wrapper from '../../../components/Wrapper';

import LuluWebp from '../../../images/Skin_Splash_Wicked_Lulu.webp';

export default function TournamentPlayers(props: any) {
    return (
        <Wrapper>
            <Head>
                <title>
                    Prokrastynatorzy - {props.tournament.name} - Zawodnicy
                </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <div className='flex flex-grow flex-col'>
                <TournamentNavigation
                    tournamentId={props.tournament.tournamentId}
                    name={props.tournament.name}
                    winner={'Hauche'}
                />

                <div className='grid h-full w-full place-items-center'>
                    <div className='flex h-5/6 w-96 flex-col items-center rounded-xl border-8 border-black bg-slate-400 pt-8'>
                        <div className='rounded-top-xl relative h-72 w-80 border-2 border-b-0 border-black bg-gray-300'>
                            <Image
                                layout='fill'
                                objectFit='cover'
                                objectPosition='center'
                                alt='test'
                                src={LuluWebp}
                            />
                        </div>
                        <div className='flex h-8 w-11/12 items-center rounded-xl border-2 border-black bg-slate-200 indent-2 font-bold'>
                            Hauche - Drugie miejsce
                        </div>
                        <div className='flex h-56 w-80 flex-col rounded-b-md border-2 border-t-0 border-black bg-gray-200 pt-1 pl-2 shadow-xl'>
                            <div>3 Lulu</div>
                            <div>1 Leblanc</div>
                        </div>
                        <div className='-mt-3 mr-8 h-8 w-24 self-end rounded-md border-2 border-black bg-slate-300 text-center text-xl font-bold'>
                            8W 3L
                        </div>
                    </div>
                </div>
            </div>
        </Wrapper>
    );
}

export async function getStaticPaths() {
    return {
        paths: [
            { params: { tournamentId: '1' } },
            { params: { tournamentId: '2' } },
        ],
        fallback: false,
    };
}

export async function getStaticProps({ params }: any) {
    return {
        props: {
            tournament: {
                tournamentId: params.tournamentId,
                name: 'Elite Bronze',
            },
        },
    };
}
