import { GetStaticPaths, GetStaticProps } from 'next';
import Head from 'next/head';
import { BrowserView } from 'react-device-detect';

import {
  getPlayerCardInfos,
  getUserById,
  PlayerCardInfo,
  pluckPlayerIds,
} from '../../../../prisma/queries';
import {
  getUserStats,
  UserStats,
} from '../../../../prisma/queries/users/getUserStats';
import {
  FaRegFlag,
  FiPercent,
  GiElfHelmet,
  GiFarmer,
  GiHood,
  GiTowerFall,
  HiOutlineEmojiHappy,
  RiEmotionSadLine,
  RiGamepadLine,
  RiKnifeBloodFill,
  RiTimerLine,
} from '../../../components/icons';
import { PlayerPageLayout } from '../../../components/layouts';
import { NextPageWithLayout } from '../../../types';
import { GlobalContext } from '../../_app';

type Paths = {
  id: string;
};

type Props = {
  user: Awaited<ReturnType<typeof getUserById>>;
  cardInfos: PlayerCardInfo[];
  userStats: UserStats;
};

type PageProps = Props & GlobalContext;

export const getStaticPaths: GetStaticPaths<Paths> = async () => {
  const userIds = await pluckPlayerIds();

  return {
    fallback: false,
    paths: userIds.map(({ id }) => ({
      params: {
        id: id.toString(),
      },
    })),
  };
};

export const getStaticProps: GetStaticProps<Props, Paths> = async (context) => {
  const userId = parseInt(context.params?.id ?? '0');
  const user = await getUserById(userId);
  const cardInfos = await getPlayerCardInfos(userId);
  const userStats = await getUserStats(userId);

  if (!user || !userStats) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      user,
      userStats,
      cardInfos,
    },
  };
};

const PlayerIndex: NextPageWithLayout<PageProps> = ({ user, userStats }) => {
  return (
    <>
      <Head>
        <title>ES - {user?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BrowserView className="flex h-full w-full flex-col justify-evenly p-8">
        <div className="flex w-full flex-col rounded-xl border-2 border-stone-500 bg-stone-800 p-4">
          <div className="mb-2 pb-2 text-2xl underline underline-offset-8">
            Mecze
          </div>
          <div className="flex w-full justify-around">
            <div className="flex items-center gap-2">
              <div title="Rozegranych gier">
                <RiGamepadLine width="3em" height="3em" />
              </div>
              <span>{userStats.wins + userStats.loses}</span>
            </div>
            <div className="flex items-center gap-2">
              <div title="Liczba wygranych">
                <HiOutlineEmojiHappy width="3em" height="3em" />
              </div>
              <span>{userStats.wins}</span>
            </div>
            <div className="flex items-center gap-2">
              <div title="Liczba przegranych">
                <RiEmotionSadLine width="3em" height="3em" />
              </div>
              <span>{userStats.loses}</span>
            </div>
            <div className="flex items-center gap-2">
              <div title="Współczynnik zwycięstw">
                <FiPercent width="3em" height="3em" />
              </div>
              <span>{userStats.winRatio + ' %'}</span>
            </div>
          </div>
        </div>

        <div className="flex gap-8">
          <div className="flex w-full flex-col rounded-xl border-2 border-stone-500 bg-stone-800 p-4">
            <div className="mb-2 pb-2 text-2xl underline underline-offset-8">
              Mecze po niebieskiej stronie
            </div>
            <div className="flex w-full justify-around">
              <div className="flex items-center gap-2">
                <div title="Rozegranych gier">
                  <RiGamepadLine width="3em" height="3em" fill="lightblue" />
                </div>
                <span>
                  {userStats.sidePreference.blue.wins +
                    userStats.sidePreference.blue.loses}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Liczba wygranych">
                  <HiOutlineEmojiHappy
                    width="3em"
                    height="3em"
                    stroke="lightblue"
                  />
                </div>
                <span>{userStats.sidePreference.blue.wins}</span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Liczba przegranych">
                  <RiEmotionSadLine width="3em" height="3em" fill="lightblue" />
                </div>
                <span>{userStats.sidePreference.blue.loses}</span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Procent zwycięstw">
                  <FiPercent width="3em" height="3em" stroke="lightblue" />
                </div>
                <span>{userStats.sidePreference.blue.winRatio + ' %'}</span>
              </div>
            </div>
          </div>

          <div className="flex w-full flex-col rounded-xl border-2 border-stone-500 bg-stone-800 p-4">
            <div className="mb-2 pb-2 text-2xl underline underline-offset-8">
              Mecze po czerwonej stronie
            </div>
            <div className="flex w-full justify-around">
              <div className="flex items-center gap-2">
                <div title="Rozegranych gier">
                  <RiGamepadLine width="3em" height="3em" fill="pink" />
                </div>
                <span>
                  {userStats.sidePreference.red.wins +
                    userStats.sidePreference.red.loses}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Liczba wygranych">
                  <HiOutlineEmojiHappy width="3em" height="3em" stroke="pink" />
                </div>
                <span>{userStats.sidePreference.red.wins}</span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Liczba przegranych">
                  <RiEmotionSadLine width="3em" height="3em" fill="pink" />
                </div>
                <span>{userStats.sidePreference.red.loses}</span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Procent zwycięstw">
                  <FiPercent width="3em" height="3em" stroke="pink" />
                </div>
                <span>{userStats.sidePreference.red.winRatio + ' %'}</span>
              </div>
            </div>
          </div>
        </div>

        <div className="flex gap-8">
          <div className="flex w-full flex-col rounded-xl border-2 border-stone-500 bg-stone-800 p-4">
            <div className="mb-2 pb-2 text-2xl underline underline-offset-8">
              Sposób wygranych
            </div>
            <div className="flex w-full justify-around">
              <div className="flex items-center gap-2">
                <div title="Pierwsza krew">
                  <RiKnifeBloodFill width="3em" height="3em" />
                </div>
                <span>{userStats.waywinStats.KILL}</span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Zabicie 100 minionów">
                  <GiFarmer width="3em" height="3em" />
                </div>
                <span>{userStats.waywinStats.CS}</span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Zniszczenie wieży">
                  <GiTowerFall width="3em" height="3em" />
                </div>
                <span>{userStats.waywinStats.TOWER}</span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Walkower">
                  <FaRegFlag width="3em" height="3em" />
                </div>
                <span>{userStats.waywinStats.SURRENDER}</span>
              </div>
            </div>
          </div>

          <div className="flex w-full flex-col rounded-xl border-2 border-stone-500 bg-stone-800 p-4">
            <div className="mb-2 pb-2 text-2xl underline underline-offset-8">
              Sposób przegranych
            </div>
            <div className="flex w-full justify-around">
              <div className="flex items-center gap-2">
                <div title="Pierwsza krew">
                  <RiKnifeBloodFill width="3em" height="3em" />
                </div>
                <span>{userStats.losewinStats.KILL}</span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Zabicie 100 minionów">
                  <GiFarmer width="3em" height="3em" />
                </div>
                <span>{userStats.losewinStats.CS}</span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Zniszczenie wieży">
                  <GiTowerFall width="3em" height="3em" />
                </div>
                <span>{userStats.losewinStats.TOWER}</span>
              </div>
              <div className="flex items-center gap-2">
                <div title="Walkower">
                  <FaRegFlag width="3em" height="3em" />
                </div>
                <span>{userStats.losewinStats.SURRENDER}</span>
              </div>
            </div>
          </div>
        </div>

        <div className="flex w-full flex-col rounded-xl border-2 border-stone-500 bg-stone-800 p-4">
          <div className="pb-2 text-2xl underline underline-offset-8">Inne</div>
          <div className="flex w-full justify-around">
            <div className="flex items-center gap-2">
              <div title="Unikalnych bohaterów">
                <GiElfHelmet width="3em" height="3em" />
              </div>
              <span>{userStats.uniqueChampions.length}</span>
            </div>
            <div className="flex items-center gap-2">
              <div title="Średnio minionów na grę">
                <GiHood width="3em" height="3em" />
              </div>
              <span>{userStats.avgCsPerGame}</span>
            </div>
            <div className="flex items-center gap-2">
              <div title="Średni czas gry">
                <RiTimerLine width="3em" height="3em" />
              </div>
              <span>{userStats.avgTimePerGame}</span>
            </div>
            <div className="flex items-center gap-2">
              <div title="Walkower">
                <FaRegFlag width="3em" height="3em" />
              </div>
              <span>{userStats.winRatio + ' %'}</span>
            </div>
          </div>
        </div>
      </BrowserView>
    </>
  );
};

PlayerIndex.getLayout = (page) => {
  return (
    <PlayerPageLayout cardInfos={page.props.cardInfos} user={page.props.user}>
      {page}
    </PlayerPageLayout>
  );
};

export default PlayerIndex;
