import Head from 'next/head';
import { Wrapper } from '../../../components/layout/Wrapper';
import { GetStaticPaths, GetStaticProps } from 'next';
import { getUserById, pluckPlayerIds } from '../../../../prisma/queries';
import { Header } from '../../../components/layout/Header';
import { PageNavigation } from '../../../components/PageNavigation';
import { useRouter } from 'next/router';

type Paths = {
  id: string;
};

interface Props {
  user: Awaited<ReturnType<typeof getUserById>>;
}

export const getStaticPaths: GetStaticPaths<Paths> = async () => {
  const userIds = await pluckPlayerIds();

  return {
    fallback: false,
    paths: userIds.map(({ id }) => ({
      params: {
        id: id.toString(),
      },
    })),
  };
};

export const getStaticProps: GetStaticProps<Props, Paths> = async (context) => {
  const userId = parseInt(context.params?.id ?? '0');
  const user = await getUserById(userId);

  if (!user) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      user,
    },
  };
};

export default function PlayerIndex({ user }: Props) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>ES - {user?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <Header />

        <div className="flex h-16 w-full p-6">
          <div className="w-1/3">
            <span className="text-4xl font-bold text-stone-300">
              {user?.name}
            </span>
          </div>

          <PageNavigation
            path={router.asPath}
            items={[
              { href: `/players/${user?.id}`, label: 'Statystyki' },
              { href: `/players/${user?.id}/champions`, label: 'Bohaterowie' },
              { href: `/players/${user?.id}/opponents`, label: 'Przeciwnicy' },
            ]}
          />
        </div>
      </Wrapper>
    </>
  );
}
