import Head from 'next/head';
import TournamentNavigation from '../../../components/tournaments/TournamentNavigation';
import Wrapper from '../../../components/layout/Wrapper';
import { GetStaticPaths, GetStaticProps } from 'next';
import { getTournament, pluckTournamentIds } from '../../../prisma/queries';
import { TournamentDTO } from '../../../types/dtos';
import { mapToTournamentDTO } from '../../../prisma/dtos/mapToTournamentDTO';
import Header from '../../../components/layout/Header';
import Breadcrumbs from '../../../components/layout/Breadcrumbs';
import { BreadcrumbsLink } from '../../../components/layout/Breadcrumbs/Breadcrumbs';

type Paths = {
  id: string;
};

interface Props {
  breadcrumbsLinks: BreadcrumbsLink[];
  tournament: TournamentDTO;
}

export default function TournamentIndex(props: Props) {
  return (
    <>
      <Head>
        <title>ES - {props.tournament.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <Header />
        <Breadcrumbs links={props.breadcrumbsLinks} />
        <TournamentNavigation
          tournamentId={props.tournament.id}
          name={props.tournament.name}
          winner={'Hauche'}
        />
      </Wrapper>
    </>
  );
}

export const getStaticPaths: GetStaticPaths<Paths> = async () => {
  const tournaments = await pluckTournamentIds();

  return {
    fallback: false,
    paths: tournaments.map(({ id }) => ({
      params: {
        id: id.toString(),
      },
    })),
  };
};

export const getStaticProps: GetStaticProps<Props, Paths> = async (context) => {
  const tournamentId = parseInt(context.params?.id ?? '0');
  const tournament = await getTournament(tournamentId);

  if (tournament == null) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      tournament: mapToTournamentDTO(tournament),
      breadcrumbsLinks: [
        { label: 'Strona główna', href: '/' },
        { label: 'Turnieje', href: '/tournaments' },
        { label: tournament.name, href: `/tournaments/${tournament.id}` },
      ],
    },
  };
};
