import Head from 'next/head';
import TournamentNavigation from '../../../components/tournaments/TournamentNavigation';
import Wrapper from '../../../components/layout/Wrapper';
import { getTournamentParams } from '../../../lib/getTournamentParams';

export default function TournamentMatches(props: any) {
  return (
    <Wrapper>
      <Head>
        <title>Prokrastynatorzy - {props.tournament.name} - MEcze</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TournamentNavigation
        tournamentId={props.tournament.tournamentId}
        name={props.tournament.name}
        winner={'Hauche'}
      />

      {props.matches.map((match) => {
        return (
          <div className="flex justify-between">
            <div></div>
            <div></div>
            <div></div>
          </div>
        );
      })}
    </Wrapper>
  );
}

export async function getStaticPaths() {
  return getTournamentParams();
}

export async function getStaticProps({ params }: any) {
  const { tournamentId } = params;

  return {
    props: {
      tournament: {
        tournamentId: params.tournamentId,
        name: 'Elite Bronze',
      },
      matches: [{ blue: {}, red: {}, general: {} }],
    },
  };
}
