import Head from 'next/head'
import Image from 'next/image'
import Wrapper from '../../components/Wrapper'
import cloudJpg from '../../assets/images/clouds.jpg'
import Link from 'next/link';


const TournamentItem = ({ tournament }: any) => (
    <Link href={`/tournaments/${tournament.tournamentId}`} passHref>
        <a className="w-full h-64 my-12 bg-stone-700 hover:text-stone-900 cursor-pointer rounded-md flex">
            <div className='h-full w-80 relative'>
                <Image layout="fill" objectFit="cover" src={cloudJpg} alt={tournament.name} />
            </div>
            <div className='text-6xl indent-8 pt-8 flex flex-col justify-between'>
                <span>{tournament.name}</span>
                <div className='h-16 text-3xl flex'>
                    <span>Graczy {tournament.playerCount}</span>
                    <span>Meczy {tournament.matchesCount}</span>
                </div>
            </div>
        </a>
    </Link>
);

interface TournamentsPageProps {
    tournaments: any[];
}

export default function Tournaments(props: TournamentsPageProps) {
  return (
    <>
      <Head>
        <title>Prokrastynatorzy - Turnieje</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <div className='flex flex-grow'>
            <div className='min-h-screen flex flex-grow flex-col'>
                <div className="h-64 w-full px-8 flex justify-between">
                    <span className="h-full indent-24 grid place-items-center text-stone-300 text-4xl">Turnieje</span>
                    <div className="h-full flex items-center">
                        <input className="text-2xl outline-none focus-visible:outline-8 focus-visible:outline-stone-800 outline-double scroll placeholder:text-stone-800 w-full h-12 bg-stone-500 rounded-md indent-4 text-stone-900" type="text" placeholder="Szukaj" />
                    </div>
                </div>
                <div className="flex-grow px-32 overflow-y-auto">
                    {props.tournaments.map((tournament) => (
                        <TournamentItem key={tournament.name} tournament={tournament} />
                    ))}
                </div>
            </div>
        </div>
      </Wrapper>
    </>
  )
}

export async function getStaticProps() {
    return {
        props: {
            tournaments: [
                { tournamentId: 1, name: 'Elite Bronze', playerCount: 16, matchesCount: 32 },
                { tournamentId: 2, name: 'Elite Bronze II', playerCount: 16, matchesCount: 32 },
                { tournamentId: 3, name: 'Elite Bronze III', playerCount: 16, matchesCount: 32 },
                { tournamentId: 4, name: 'Elite Bronze IV', playerCount: 16, matchesCount: 32 },
                { tournamentId: 5, name: 'Elite Bronze V', playerCount: 16, matchesCount: 32 },
            ]
        }
    }
}