import Head from 'next/head';
import Header from '../../components/layout/Header';
import Wrapper from '../../components/layout/Wrapper';
import TournamentItem from '../../components/tournaments/TournamentItem';
import TournamentList from '../../components/tournaments/TournamentList';
import { getTournaments } from '../../prisma/queries/tournaments';
import { TournamentIndexDTO } from '../../types/tournament.dto';

interface TournamentsPageProps {
  tournaments: TournamentIndexDTO[];
}

export default function Tournaments(props: TournamentsPageProps) {
  return (
    <>
      <Head>
        <title>Elite Silver - Turnieje</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <Header />
        <div className="flex flex-grow flex-col p-4">
          <span className="text-4xl text-stone-300">Turnieje</span>

          <TournamentList tournaments={props.tournaments} />
        </div>
      </Wrapper>
    </>
  );
}

export async function getStaticProps() {
  const tournaments = await getTournaments();

  return {
    props: {
      tournaments,
    },
  };
}
