import Head from 'next/head';
import Breadcrumbs from '../../components/layout/Breadcrumbs';
import { BreadcrumbsLink } from '../../components/layout/Breadcrumbs/Breadcrumbs';
import Header from '../../components/layout/Header';
import Wrapper from '../../components/layout/Wrapper';

interface PlayersPageProps {
  breadcrumbsLinks: BreadcrumbsLink[];
}

export default function Players(props: PlayersPageProps) {
  return (
    <>
      <Head>
        <title>Elite Silver - Zawodnicy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <Header />
        <Breadcrumbs links={props.breadcrumbsLinks} />
      </Wrapper>
    </>
  );
}

export async function getStaticProps() {
  const breadcrumbsLinks = [
    { label: 'Strona główna', href: '/' },
    { label: 'Zawodnicy', href: '/stats' },
  ];

  return {
    props: {
      breadcrumbsLinks,
    },
  };
}
