import Head from 'next/head';
import Wrapper from 'components/layout/Wrapper';
import Header from '../components/layout/Header';

export default function Index() {
  return (
    <>
      <Head>
        <title>Elite Silver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <Header />
      </Wrapper>
    </>
  );
}
