import Head from 'next/head';
import { Wrapper } from '../../components/layout/Wrapper';

export default function Account() {
  return (
    <>
      <Head>
        <title>ES - Konto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper></Wrapper>
    </>
  );
}
