import Head from 'next/head';
import Image from 'next/image';
import Wrapper from '../../components/Wrapper';
import cloudJpg from '../../images/clouds.jpg';
import Link from 'next/link';

const TournamentItem = ({ tournament }: any) => (
    <Link href={`/tournaments/${tournament.tournamentId}`} passHref>
        <a className='my-12 flex h-64 w-full cursor-pointer rounded-md bg-stone-700 hover:text-stone-900'>
            <div className='relative h-full w-80'>
                <Image
                    layout='fill'
                    objectFit='cover'
                    src={cloudJpg}
                    alt={tournament.name}
                />
            </div>
            <div className='flex flex-col justify-between pt-8 indent-8 text-6xl'>
                <span>{tournament.name}</span>
                <div className='flex h-16 text-3xl'>
                    <span>Graczy {tournament.playerCount}</span>
                    <span>Meczy {tournament.matchesCount}</span>
                </div>
            </div>
        </a>
    </Link>
);

interface TournamentsPageProps {
    tournaments: any[];
}

export default function Tournaments(props: TournamentsPageProps) {
    return (
        <>
            <Head>
                <title>Prokrastynatorzy - Turnieje</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Wrapper>
                <div className='flex flex-grow'>
                    <div className='flex min-h-screen flex-grow flex-col'>
                        <div className='flex h-64 w-full justify-between px-8'>
                            <span className='grid h-full place-items-center indent-24 text-4xl text-stone-300'>
                                Turnieje
                            </span>
                            <div className='flex h-full items-center'>
                                <input
                                    className='scroll h-12 w-full rounded-md bg-stone-500 indent-4 text-2xl text-stone-900 outline-none outline-double placeholder:text-stone-800 focus-visible:outline-8 focus-visible:outline-stone-800'
                                    type='text'
                                    placeholder='Szukaj'
                                />
                            </div>
                        </div>
                        <div className='flex-grow overflow-y-auto px-32'>
                            {props.tournaments.map((tournament) => (
                                <TournamentItem
                                    key={tournament.name}
                                    tournament={tournament}
                                />
                            ))}
                        </div>
                    </div>
                </div>
            </Wrapper>
        </>
    );
}

export async function getStaticProps() {
    return {
        props: {
            tournaments: [
                {
                    tournamentId: 1,
                    name: 'Elite Bronze',
                    playerCount: 16,
                    matchesCount: 32,
                },
                {
                    tournamentId: 2,
                    name: 'Elite Bronze II',
                    playerCount: 16,
                    matchesCount: 32,
                },
                {
                    tournamentId: 3,
                    name: 'Elite Bronze III',
                    playerCount: 16,
                    matchesCount: 32,
                },
                {
                    tournamentId: 4,
                    name: 'Elite Bronze IV',
                    playerCount: 16,
                    matchesCount: 32,
                },
                {
                    tournamentId: 5,
                    name: 'Elite Bronze V',
                    playerCount: 16,
                    matchesCount: 32,
                },
            ],
        },
    };
}
